export type SyntaxPalette = {
    keyword: string;
    string: string;
    comment: string;
    number: string;
    function: string;
    type: string;
    variable: string;
    operator: string;
    tag: string;
    attribute: string;
    builtin: string;
    meta: string;
    literal: string;
    title: string;
};

export type ScreenshotTheme = {
    label: string;
    description: string;
    background: string;
    border: string;
    headerBackground: string;
    headerText: string;
    codeText: string;
    lineNumber: string;
    palette: SyntaxPalette;
};

export const DEFAULT_THEME_ID = 'vscode-dark';

export const SCREENSHOT_THEMES: Record<string, ScreenshotTheme> = {
    'vscode-dark': {
        label: 'VS Code Dark',
        description: 'Default — matches the VS Code editor',
        background: '#1e1e1e',
        border: '#2d2d2d',
        headerBackground: '#252526',
        headerText: '#cccccc',
        codeText: '#d4d4d4',
        lineNumber: '#858585',
        palette: {
            keyword: '#569cd6',
            string: '#d69d85',
            comment: '#57a64a',
            number: '#b5cea8',
            function: '#dcdcaa',
            type: '#4ec9b0',
            variable: '#9cdcfe',
            operator: '#b4b4b4',
            tag: '#569cd6',
            attribute: '#9cdcfe',
            builtin: '#4ec9b0',
            meta: '#9b9b9b',
            literal: '#569cd6',
            title: '#dcdcaa',
        },
    },
    'vscode-light': {
        label: 'VS Code Light',
        description: 'Clean light theme, good for printed docs',
        background: '#ffffff',
        border: '#e1e4e8',
        headerBackground: '#f3f3f3',
        headerText: '#333333',
        codeText: '#000000',
        lineNumber: '#237893',
        palette: {
            keyword: '#0000ff',
            string: '#a31515',
            comment: '#008000',
            number: '#098658',
            function: '#795e26',
            type: '#267f99',
            variable: '#001080',
            operator: '#000000',
            tag: '#800000',
            attribute: '#ff0000',
            builtin: '#267f99',
            meta: '#a31515',
            literal: '#0000ff',
            title: '#795e26',
        },
    },
    'github-dark': {
        label: 'GitHub Dark',
        description: "Matches GitHub's dark mode",
        background: '#0d1117',
        border: '#30363d',
        headerBackground: '#161b22',
        headerText: '#c9d1d9',
        codeText: '#c9d1d9',
        lineNumber: '#6e7681',
        palette: {
            keyword: '#ff7b72',
            string: '#a5d6ff',
            comment: '#8b949e',
            number: '#79c0ff',
            function: '#d2a8ff',
            type: '#ffa657',
            variable: '#ffa657',
            operator: '#ff7b72',
            tag: '#7ee787',
            attribute: '#79c0ff',
            builtin: '#ffa657',
            meta: '#8b949e',
            literal: '#79c0ff',
            title: '#d2a8ff',
        },
    },
    'github-light': {
        label: 'GitHub Light',
        description: "Matches GitHub's light mode",
        background: '#ffffff',
        border: '#d0d7de',
        headerBackground: '#f6f8fa',
        headerText: '#24292f',
        codeText: '#24292f',
        lineNumber: '#8c959f',
        palette: {
            keyword: '#cf222e',
            string: '#0a3069',
            comment: '#6e7781',
            number: '#0550ae',
            function: '#8250df',
            type: '#953800',
            variable: '#953800',
            operator: '#cf222e',
            tag: '#116329',
            attribute: '#0550ae',
            builtin: '#953800',
            meta: '#6e7781',
            literal: '#0550ae',
            title: '#8250df',
        },
    },
    monokai: {
        label: 'Monokai',
        description: 'Classic warm dark theme',
        background: '#272822',
        border: '#3e3d32',
        headerBackground: '#1e1f1c',
        headerText: '#f8f8f2',
        codeText: '#f8f8f2',
        lineNumber: '#75715e',
        palette: {
            keyword: '#f92672',
            string: '#e6db74',
            comment: '#75715e',
            number: '#ae81ff',
            function: '#a6e22e',
            type: '#66d9ef',
            variable: '#fd971f',
            operator: '#f92672',
            tag: '#f92672',
            attribute: '#a6e22e',
            builtin: '#66d9ef',
            meta: '#75715e',
            literal: '#ae81ff',
            title: '#a6e22e',
        },
    },
    dracula: {
        label: 'Dracula',
        description: 'Popular purple-tinted dark theme',
        background: '#282a36',
        border: '#44475a',
        headerBackground: '#21222c',
        headerText: '#f8f8f2',
        codeText: '#f8f8f2',
        lineNumber: '#6272a4',
        palette: {
            keyword: '#ff79c6',
            string: '#f1fa8c',
            comment: '#6272a4',
            number: '#bd93f9',
            function: '#50fa7b',
            type: '#8be9fd',
            variable: '#ffb86c',
            operator: '#ff79c6',
            tag: '#ff79c6',
            attribute: '#50fa7b',
            builtin: '#8be9fd',
            meta: '#6272a4',
            literal: '#bd93f9',
            title: '#50fa7b',
        },
    },
    nord: {
        label: 'Nord',
        description: 'Cool arctic dark theme',
        background: '#2e3440',
        border: '#3b4252',
        headerBackground: '#3b4252',
        headerText: '#eceff4',
        codeText: '#d8dee9',
        lineNumber: '#4c566a',
        palette: {
            keyword: '#81a1c1',
            string: '#a3be8c',
            comment: '#616e88',
            number: '#b48ead',
            function: '#88c0d0',
            type: '#8fbcbb',
            variable: '#d8dee9',
            operator: '#81a1c1',
            tag: '#81a1c1',
            attribute: '#8fbcbb',
            builtin: '#8fbcbb',
            meta: '#5e81ac',
            literal: '#81a1c1',
            title: '#88c0d0',
        },
    },
    'solarized-dark': {
        label: 'Solarized Dark',
        description: 'Ethan Schoonover’s low-contrast dark palette',
        background: '#002b36',
        border: '#073642',
        headerBackground: '#073642',
        headerText: '#93a1a1',
        codeText: '#839496',
        lineNumber: '#586e75',
        palette: {
            keyword: '#859900',
            string: '#2aa198',
            comment: '#586e75',
            number: '#d33682',
            function: '#268bd2',
            type: '#b58900',
            variable: '#268bd2',
            operator: '#859900',
            tag: '#268bd2',
            attribute: '#b58900',
            builtin: '#cb4b16',
            meta: '#586e75',
            literal: '#d33682',
            title: '#268bd2',
        },
    },
    'solarized-light': {
        label: 'Solarized Light',
        description: 'Ethan Schoonover’s low-contrast light palette',
        background: '#fdf6e3',
        border: '#eee8d5',
        headerBackground: '#eee8d5',
        headerText: '#586e75',
        codeText: '#657b83',
        lineNumber: '#93a1a1',
        palette: {
            keyword: '#859900',
            string: '#2aa198',
            comment: '#93a1a1',
            number: '#d33682',
            function: '#268bd2',
            type: '#b58900',
            variable: '#268bd2',
            operator: '#859900',
            tag: '#268bd2',
            attribute: '#b58900',
            builtin: '#cb4b16',
            meta: '#93a1a1',
            literal: '#d33682',
            title: '#268bd2',
        },
    },
    'one-dark': {
        label: 'Atom One Dark',
        description: 'Atom editor’s dark theme',
        background: '#282c34',
        border: '#3e4451',
        headerBackground: '#21252b',
        headerText: '#abb2bf',
        codeText: '#abb2bf',
        lineNumber: '#5c6370',
        palette: {
            keyword: '#c678dd',
            string: '#98c379',
            comment: '#5c6370',
            number: '#d19a66',
            function: '#61afef',
            type: '#e5c07b',
            variable: '#e06c75',
            operator: '#56b6c2',
            tag: '#e06c75',
            attribute: '#d19a66',
            builtin: '#e5c07b',
            meta: '#61afef',
            literal: '#56b6c2',
            title: '#61afef',
        },
    },
    'one-light': {
        label: 'Atom One Light',
        description: 'Atom editor’s light theme',
        background: '#fafafa',
        border: '#e5e5e6',
        headerBackground: '#eaeaeb',
        headerText: '#383a42',
        codeText: '#383a42',
        lineNumber: '#9d9d9f',
        palette: {
            keyword: '#a626a4',
            string: '#50a14f',
            comment: '#a0a1a7',
            number: '#986801',
            function: '#4078f2',
            type: '#c18401',
            variable: '#e45649',
            operator: '#0184bc',
            tag: '#e45649',
            attribute: '#986801',
            builtin: '#c18401',
            meta: '#4078f2',
            literal: '#0184bc',
            title: '#4078f2',
        },
    },
};

export function getScreenshotTheme(themeId: string): ScreenshotTheme {
    return SCREENSHOT_THEMES[themeId] ?? SCREENSHOT_THEMES[DEFAULT_THEME_ID];
}
